# Generated by Django 2.0.2 on 2018-04-06 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch_course', '0002_auto_20180406_1917'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch_course.Course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_index',
            field=models.IntegerField(null=True),
        ),
    ]
