# Generated by Django 2.0.2 on 2018-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180406_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_src',
            field=models.ImageField(blank=True, default='sampleavatar.png', upload_to=''),
        ),
    ]
