# Generated by Django 2.0.2 on 2018-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180318_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
