# Generated by Django 2.0.2 on 2018-04-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_answer_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Answer',
            new_name='Skill',
        ),
    ]
