# Generated by Django 2.0.2 on 2018-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20180402_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='weight',
            field=models.FloatField(),
        ),
    ]
