# Generated by Django 2.0.2 on 2018-04-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20180421_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='body_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='body_ar',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
