# Generated by Django 2.0.2 on 2018-04-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20180412_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(db_column='slug', default=None, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
    ]
