# Generated by Django 2.0.1 on 2018-04-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='link',
        ),
        migrations.AddField(
            model_name='course',
            name='links',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
